# 🔢 Estudos de Numpy - Projeto Descomplica

Este notebook é dedicado ao estudo de **Numerical Python (Numpy)**, focando em performance, manipulação de arrays multidimensionais e vetorização.

In [68]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print(f"Numpy version: {np.__version__}")

Numpy version: 2.1.3


In [69]:
d = [1, 2, 3, 4, 5, 6]
arr = np.array(d)
arr

array([1, 2, 3, 4, 5, 6])

In [70]:
arr.dtype

dtype('int64')

In [71]:
np.shape(arr)

(6,)

In [72]:
np.size(arr)

6

In [73]:
d2 = [[1,3,5,7], [3,55,6,90]]
arr1 = np.array(d2)
arr1

array([[ 1,  3,  5,  7],
       [ 3, 55,  6, 90]])

In [74]:
np.shape(arr1)

(2, 4)

In [75]:
arr1[1,2]

np.int64(6)

In [76]:
arr1[0, :]

array([1, 3, 5, 7])

In [77]:
arr1[1, 1:3]

array([55,  6])

In [78]:
np.empty(6, dtype='int32')

array([-1445704912,       32453,   228689632,           0,          32,
                 0], dtype=int32)

In [79]:
np.empty([2,2], dtype='int32')

array([[3, 0],
       [3, 0]], dtype=int32)

In [80]:
np.random.randint(0,57, size=(3,3))

array([[53, 35, 15],
       [42, 50,  6],
       [ 2,  9, 31]])

In [81]:
np.random.rand(3,3)

array([[0.13987399, 0.35769214, 0.79742172],
       [0.08675168, 0.05937734, 0.92538928],
       [0.13371436, 0.48933388, 0.46100264]])

In [82]:
arr1

array([[ 1,  3,  5,  7],
       [ 3, 55,  6, 90]])

In [83]:
arr3 = arr1 * 2
arr3

array([[  2,   6,  10,  14],
       [  6, 110,  12, 180]])

In [84]:
arr33 = arr1 / 2
arr3

array([[  2,   6,  10,  14],
       [  6, 110,  12, 180]])

In [85]:
arr333 = arr1 + 2
arr3

array([[  2,   6,  10,  14],
       [  6, 110,  12, 180]])

In [86]:
subarr = np.subtract(arr3, arr1)
subarr

array([[ 1,  3,  5,  7],
       [ 3, 55,  6, 90]])

In [87]:
arr1.mean()

np.float64(21.25)

In [88]:
arr1.cumsum(axis=1)

array([[  1,   4,   9,  16],
       [  3,  58,  64, 154]])

In [89]:
arr1.cumsum(axis=0)

array([[ 1,  3,  5,  7],
       [ 4, 58, 11, 97]])

In [91]:
arr4 = np.arange(8)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7])

In [93]:
arr5 = arr4.reshape(4,2)
arr5

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [95]:
arr6 = arr5.reshape(2,4)
arr6

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [96]:
arr7 = arr6.T
arr7

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [97]:
arr8 = arr7.T
arr8

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [103]:
arr9 = np.concatenate((arr5, arr7), axis=1)
arr9

array([[0, 1, 0, 4],
       [2, 3, 1, 5],
       [4, 5, 2, 6],
       [6, 7, 3, 7]])

In [107]:
np.split(arr7, 2)

[array([[0, 4],
        [1, 5]]),
 array([[2, 6],
        [3, 7]])]

In [116]:
arr10 = np.ones(10)
arr10

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])